# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField()),
                ('meta_content', models.TextField()),
                ('meta_title', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Magic word')),
            ],
        ),
    ]
